name: grades
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  studentvueclient:
    path: ./lib/studentvue
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  iconsax: ^0.0.8
  carousel_slider: ^5.0.0
  fl_chart: ^0.68.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
