// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ZB9iq9ei7hdRCGDUTP2FUiLmyIGbLas',
    appId: '1:97207396987:web:9f97cea4a0bfd4d6e310de',
    messagingSenderId: '97207396987',
    projectId: 'genesis-317af',
    authDomain: 'genesis-317af.firebaseapp.com',
    storageBucket: 'genesis-317af.appspot.com',
    measurementId: 'G-425NS1G3Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZEALowgMWVcI8LzlnHPMSi5bNi-L4VNw',
    appId: '1:97207396987:android:db80a07cafd61bf6e310de',
    messagingSenderId: '97207396987',
    projectId: 'genesis-317af',
    storageBucket: 'genesis-317af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHlBGpCTHud8P2xOY4LgDozBYRd3vtqdg',
    appId: '1:97207396987:ios:fd90ea7467b002e1e310de',
    messagingSenderId: '97207396987',
    projectId: 'genesis-317af',
    storageBucket: 'genesis-317af.appspot.com',
    iosBundleId: 'com.example.grades11242',
  );

}